#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as the shell interpreter:
#           sh -c 'SETUP' script_to_run
#
#       See https://www.gnu.org/software/bash/manual/bash.html#Shell-Scripts
#           for more about porting shell scripts.
#
#   (2) The script will attempt to find a gradle installation in the following
#       order (with fallbacks if not found):
#
#           (a) Whatever is specified by the `GRADLE_HOME` environment variable
#           (b) The Gradle distribution specified by the `gradle-wrapper.properties`
#               file's `distributionUrl` property (used by the Gradle Wrapper).
#           (c) A Gradle distribution found on the path under the executable's
#               name, as per the `gradle` command.
#           (d) A "gradle" executable on the system path.
#
#       If a Gradle distribution cannot be found, the script will print a
#       message and exit.
#
#   (3) This script only uses POSIX `sh` syntax. It does not support all features
#       of Bash or other shells.
#
#   For developers, this script uses the following non-POSIX features:
#
#       - Using a star to expand the list of arguments after `-P` options:
#           `-P`* : Expand the following option's argument as an array of arguments.
#
#       This is required to properly handle the `-P` argument used to set
#       properties. It should be safe to do so because POSIX leaves this behavior
#       unspecified.
#
#       In particular, this script supports:
#
#           - Default Gradle Wrapper behavior.
#           - Interactive command line prompt for the '-p' argument.
#           - Wrapper script redirection of output on the `-q` and `-s` arguments.
#
#       The majority of the Bourne shell features used are covered by the POSIX
#       standard, including:
#
#           - Variable assignment and expansion.
#           - The `for`, `case`, and `while` loops.
#           - The use of functions to encapsume the script's logic.
#
#       However, the following Bash-specific features are not supported:
#
#           - The `function` keyword to define a function.
#           - Array assignment and indexed access.
#           - The `local` keyword to define local variables.
#           - Advanced pattern matching (including extended globbing).
#           - Process substitution (`<(cmd)` and `>(cmd)`).
#
#       For more information on how Gradle works, please see the Gradle User Guide at
#           https://docs.gradle.org/current/userguide/userguide.html
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H -n is not supported. POSIX sh only supports ulimit -n.
        # We may not want to set the hard limit because doing so may be too restrictive.
        # However, we set a soft limit that is at least the current soft limit and at most the hard limit.
        soft_limit=$( ulimit -n -S )
        hard_limit=$( ulimit -n -H )
        if [ $soft_limit -le $hard_limit ] ; then
            if [ $MAX_FD -gt $soft_limit ] ; then
                MAX_FD=$soft_limit
            fi
        else
            MAX_FD=$hard_limit
        fi
        ;;
      * )
        MAX_FD="$MAX_FD"
        ;;
    esac
    if [ "$MAX_FD" -gt 0 ]; then
        ulimit -n "$MAX_FD"
    fi
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * the classpath
#   * the default JVM options
#   * the end of options (--), which is consumed to prevent argument mixing,
#     to make sure options like -d32 or -d64 are correctly handled.

# See https://docs.oracle.com/en/java/javase/11/tools/java.html#GUID-BE93ABDC-999C-4CB5-A88C-6219C8420F1C
# for the documentation of all the non-standard options.

# The following globs are separate to avoid being interpreted as spaces between
# the pattern and the arguments, which may be required for substrings with
# spaces in them.

# First, collect all of the arguments from the command line, including
# the script name (the 0th argument) and any argument not processed by the
# special argument processing.
# Use the location of the script to locate the `gradle-wrapper.jar` and its
# dependencies. We assume that the script is located in the same directory as
# the gradle-wrapper.jar file.
# We can't use associative arrays in POSIX sh, so we use the positional
# parameters, which we set to the arguments to pass to the Java command.

# If we are on Windows, we are going to use `cmd` to run the script, so we
# need to make sure that we can process the arguments. This is needed because
# on Windows, arguments are passed as a single string to the script, not split
# into individual arguments. Use `set --` to split the arguments.
if $cygwin || $msys; then
    set -- $( echo "$@" | sed 's/\\/\//g' )
fi

# Collect the arguments to the wrapper shell script.
# The first argument is the script name (the 0th argument).
# For POSIX sh, we can use the special parameter `$@` to get all the arguments.
# However, we can't use `$@` if there are quoted arguments, because the
# expansion will be a single string with the quotes intact. To solve this,
# we'll quote the arguments and let the Java command handle the quotes.
# However, we must first remove the script name from the list of arguments.
# Removing the script name from the start of the list.
# Use the `shift` command to remove the first argument.

# The arguments from the command line are stored in `$@`, which includes the
# script name. We need to remove it.
shift

# Collect the arguments to the wrapper script.
WRAPPER_ARGS="$@"

# The following is the Java command to run the wrapper.
# shellcheck disable=SC2086
# We have to quote the arguments because they are being passed to a command
# substitution. The command substitution will use the arguments as separate
# entries in the array. However, we want the arguments to be treated as a single
# string. To do that, we quote the entire command line. Unfortunately, we can't
# do that because the command substitution will always break the quotes. So we
# use the workaround of appending the arguments as a string to the Java command.
# However, the Java command will then treat the arguments as a single string
# unless we also use the `-Xss` option to set the stack size, which is not
# guaranteed to be available. To work around this, we set the `-Djava.security.manager`
# option to an empty string, which tells the Java command to treat the arguments
# as separate arguments.
# This workaround works for Java 8 and later.
exec "$JAVACMD" ${JAVA_OPTS:-} ${GRADLE_OPTS:-} ${DEFAULT_JVM_OPTS:-} \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    ${WRAPPER_ARGS:-}
